-- Club event day-of check-ins (desk / QR / walk-in)
CREATE TABLE IF NOT EXISTS `club_event_check_ins` (
  `id` VARCHAR(191) NOT NULL,
  `owner_id` VARCHAR(191) NOT NULL,
  `trial_session_id` VARCHAR(36) NOT NULL DEFAULT 'prod',
  `profile_id` VARCHAR(191) NOT NULL,
  `event_id` VARCHAR(191) NOT NULL,
  `member_id` VARCHAR(191) NULL,
  `guest_name` VARCHAR(160) NOT NULL,
  `guest_phone` VARCHAR(32) NOT NULL DEFAULT '',
  `member_code` VARCHAR(64) NOT NULL DEFAULT '',
  `source` VARCHAR(16) NOT NULL DEFAULT 'STAFF',
  `submission_id` VARCHAR(191) NULL,
  `checked_in_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `fulfillment_json` TEXT NOT NULL,
  `payment_due_baht` INT NOT NULL DEFAULT 0,
  `payment_cleared` BOOLEAN NOT NULL DEFAULT false,
  `signature_image_url` VARCHAR(512) NULL,
  `signed_at` DATETIME(3) NULL,
  `note` VARCHAR(500) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `club_event_checkin_event_time_idx`(`event_id`, `checked_in_at`),
  INDEX `club_event_checkin_profile_event_idx`(`profile_id`, `event_id`),
  INDEX `club_event_checkin_owner_trial_idx`(`owner_id`, `trial_session_id`),
  CONSTRAINT `club_event_check_ins_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `club_event_check_ins_profile_id_fkey` FOREIGN KEY (`profile_id`) REFERENCES `club_event_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `club_event_check_ins_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `club_event_records`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
