-- Asset Management module: categories/departments/locations/suppliers/assets
-- transactions/maintenances/disposals/audits/settings

CREATE TABLE `asset_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` VARCHAR(191) NOT NULL,
  `trial_session_id` VARCHAR(36) NOT NULL DEFAULT 'prod',
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `depreciation_years` INT NOT NULL DEFAULT 5,
  `description` TEXT NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT true,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ast_cat_owner_trial_code_uidx` (`owner_id`, `trial_session_id`, `code`),
  INDEX `ast_cat_owner_trial_active_idx` (`owner_id`, `trial_session_id`, `is_active`),
  CONSTRAINT `asset_categories_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `asset_departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` VARCHAR(191) NOT NULL,
  `trial_session_id` VARCHAR(36) NOT NULL DEFAULT 'prod',
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `head_person_name` VARCHAR(120) NULL,
  `description` TEXT NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT true,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ast_dep_owner_trial_code_uidx` (`owner_id`, `trial_session_id`, `code`),
  INDEX `ast_dep_owner_trial_active_idx` (`owner_id`, `trial_session_id`, `is_active`),
  CONSTRAINT `asset_departments_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `asset_locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` VARCHAR(191) NOT NULL,
  `trial_session_id` VARCHAR(36) NOT NULL DEFAULT 'prod',
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `building` VARCHAR(120) NULL,
  `floor` VARCHAR(20) NULL,
  `room` VARCHAR(40) NULL,
  `description` TEXT NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT true,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ast_loc_owner_trial_code_uidx` (`owner_id`, `trial_session_id`, `code`),
  INDEX `ast_loc_owner_trial_active_idx` (`owner_id`, `trial_session_id`, `is_active`),
  CONSTRAINT `asset_locations_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `asset_suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` VARCHAR(191) NOT NULL,
  `trial_session_id` VARCHAR(36) NOT NULL DEFAULT 'prod',
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(160) NOT NULL,
  `contact_person` VARCHAR(120) NULL,
  `phone` VARCHAR(40) NULL,
  `email` VARCHAR(160) NULL,
  `address` TEXT NULL,
  `tax_id` VARCHAR(40) NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT true,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ast_sup_owner_trial_code_uidx` (`owner_id`, `trial_session_id`, `code`),
  INDEX `ast_sup_owner_trial_active_idx` (`owner_id`, `trial_session_id`, `is_active`),
  CONSTRAINT `asset_suppliers_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `assets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` VARCHAR(191) NOT NULL,
  `trial_session_id` VARCHAR(36) NOT NULL DEFAULT 'prod',
  `asset_code` VARCHAR(40) NOT NULL,
  `asset_name` VARCHAR(200) NOT NULL,
  `category_id` INT NULL,
  `brand` VARCHAR(120) NULL,
  `model` VARCHAR(160) NULL,
  `serial_number` VARCHAR(160) NULL,
  `description` TEXT NULL,
  `purchase_date` DATE NULL,
  `purchase_price` DECIMAL(14,2) NULL,
  `supplier_id` INT NULL,
  `warranty_until` DATE NULL,
  `depreciation_years` INT NOT NULL DEFAULT 5,
  `current_value` DECIMAL(14,2) NULL,
  `status` ENUM('AVAILABLE','IN_USE','BORROWED','IN_REPAIR','DISPOSED') NOT NULL DEFAULT 'AVAILABLE',
  `condition` ENUM('GOOD','FAIR','POOR','BROKEN') NOT NULL DEFAULT 'GOOD',
  `location_id` INT NULL,
  `department_id` INT NULL,
  `holder_name` VARCHAR(120) NULL,
  `image_url` VARCHAR(512) NULL,
  `qr_code` VARCHAR(80) NULL,
  `note` TEXT NULL,
  `is_deleted` BOOLEAN NOT NULL DEFAULT false,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ast_asset_owner_trial_code_uidx` (`owner_id`, `trial_session_id`, `asset_code`),
  INDEX `ast_asset_owner_trial_status_idx` (`owner_id`, `trial_session_id`, `status`, `is_deleted`),
  INDEX `ast_asset_owner_trial_cat_idx` (`owner_id`, `trial_session_id`, `category_id`),
  INDEX `ast_asset_owner_trial_dept_idx` (`owner_id`, `trial_session_id`, `department_id`),
  INDEX `ast_asset_owner_trial_loc_idx` (`owner_id`, `trial_session_id`, `location_id`),
  CONSTRAINT `assets_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `assets_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `asset_categories`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `assets_supplier_id_fkey` FOREIGN KEY (`supplier_id`) REFERENCES `asset_suppliers`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `assets_location_id_fkey` FOREIGN KEY (`location_id`) REFERENCES `asset_locations`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `assets_department_id_fkey` FOREIGN KEY (`department_id`) REFERENCES `asset_departments`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `asset_transactions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_id` VARCHAR(191) NOT NULL,
  `trial_session_id` VARCHAR(36) NOT NULL DEFAULT 'prod',
  `transaction_code` VARCHAR(40) NOT NULL,
  `type` ENUM('ASSIGN','BORROW','RETURN','TRANSFER') NOT NULL,
  `asset_id` INT NOT NULL,
  `from_location_id` INT NULL,
  `to_location_id` INT NULL,
  `from_holder_name` VARCHAR(120) NULL,
  `to_holder_name` VARCHAR(120) NULL,
  `transaction_date` DATE NOT NULL,
  `expected_return_date` DATE NULL,
  `actual_return_date` DATE NULL,
  `status` ENUM('ACTIVE','COMPLETED','CANCELLED') NOT NULL DEFAULT 'ACTIVE',
  `note` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ast_tx_owner_trial_code_uidx` (`owner_id`, `trial_session_id`, `transaction_code`),
  INDEX `ast_tx_owner_trial_date_idx` (`owner_id`, `trial_session_id`, `transaction_date`),
  INDEX `ast_tx_asset_idx` (`asset_id`),
  CONSTRAINT `asset_transactions_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `asset_transactions_asset_id_fkey` FOREIGN KEY (`asset_id`) REFERENCES `assets`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `asset_transactions_from_location_id_fkey` FOREIGN KEY (`from_location_id`) REFERENCES `asset_locations`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `asset_transactions_to_location_id_fkey` FOREIGN KEY (`to_location_id`) REFERENCES `asset_locations`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `asset_maintenances` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_id` VARCHAR(191) NOT NULL,
  `trial_session_id` VARCHAR(36) NOT NULL DEFAULT 'prod',
  `maintenance_code` VARCHAR(40) NOT NULL,
  `asset_id` INT NOT NULL,
  `type` ENUM('PREVENTIVE','CORRECTIVE') NOT NULL DEFAULT 'CORRECTIVE',
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `cost` DECIMAL(14,2) NULL,
  `vendor` VARCHAR(160) NULL,
  `description` TEXT NULL,
  `result` TEXT NULL,
  `status` ENUM('IN_PROGRESS','COMPLETED','CANCELLED') NOT NULL DEFAULT 'IN_PROGRESS',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ast_mt_owner_trial_code_uidx` (`owner_id`, `trial_session_id`, `maintenance_code`),
  INDEX `ast_mt_owner_trial_date_idx` (`owner_id`, `trial_session_id`, `start_date`),
  INDEX `ast_mt_asset_idx` (`asset_id`),
  CONSTRAINT `asset_maintenances_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `asset_maintenances_asset_id_fkey` FOREIGN KEY (`asset_id`) REFERENCES `assets`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `asset_disposals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_id` VARCHAR(191) NOT NULL,
  `trial_session_id` VARCHAR(36) NOT NULL DEFAULT 'prod',
  `disposal_code` VARCHAR(40) NOT NULL,
  `asset_id` INT NOT NULL,
  `disposal_date` DATE NOT NULL,
  `reason` TEXT NULL,
  `method` ENUM('SALE','DONATION','WRITE_OFF','RECYCLE') NOT NULL DEFAULT 'SALE',
  `sale_price` DECIMAL(14,2) NULL,
  `buyer` VARCHAR(160) NULL,
  `approved_by_name` VARCHAR(120) NULL,
  `document_url` VARCHAR(512) NULL,
  `note` TEXT NULL,
  `status` ENUM('PENDING','COMPLETED','CANCELLED') NOT NULL DEFAULT 'COMPLETED',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ast_dp_owner_trial_code_uidx` (`owner_id`, `trial_session_id`, `disposal_code`),
  INDEX `ast_dp_owner_trial_date_idx` (`owner_id`, `trial_session_id`, `disposal_date`),
  INDEX `ast_dp_asset_idx` (`asset_id`),
  CONSTRAINT `asset_disposals_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `asset_disposals_asset_id_fkey` FOREIGN KEY (`asset_id`) REFERENCES `assets`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `asset_audits` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_id` VARCHAR(191) NOT NULL,
  `trial_session_id` VARCHAR(36) NOT NULL DEFAULT 'prod',
  `audit_code` VARCHAR(40) NOT NULL,
  `audit_date` DATE NOT NULL,
  `auditor_name` VARCHAR(120) NULL,
  `asset_id` INT NOT NULL,
  `expected_location_id` INT NULL,
  `actual_location_id` INT NULL,
  `expected_condition` ENUM('GOOD','FAIR','POOR','BROKEN') NULL,
  `actual_condition` ENUM('GOOD','FAIR','POOR','BROKEN') NULL,
  `status` ENUM('MATCH','MISMATCH','MISSING') NOT NULL DEFAULT 'MATCH',
  `note` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ast_au_owner_trial_code_uidx` (`owner_id`, `trial_session_id`, `audit_code`),
  INDEX `ast_au_owner_trial_date_idx` (`owner_id`, `trial_session_id`, `audit_date`),
  INDEX `ast_au_asset_idx` (`asset_id`),
  CONSTRAINT `asset_audits_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `asset_audits_asset_id_fkey` FOREIGN KEY (`asset_id`) REFERENCES `assets`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `asset_audits_expected_location_id_fkey` FOREIGN KEY (`expected_location_id`) REFERENCES `asset_locations`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `asset_audits_actual_location_id_fkey` FOREIGN KEY (`actual_location_id`) REFERENCES `asset_locations`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `asset_settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` VARCHAR(191) NOT NULL,
  `trial_session_id` VARCHAR(36) NOT NULL DEFAULT 'prod',
  `org_name` VARCHAR(160) NULL,
  `org_address` TEXT NULL,
  `org_phone` VARCHAR(40) NULL,
  `org_email` VARCHAR(160) NULL,
  `asset_prefix` VARCHAR(10) NOT NULL DEFAULT 'AST',
  `tx_prefix` VARCHAR(10) NOT NULL DEFAULT 'TX',
  `mt_prefix` VARCHAR(10) NOT NULL DEFAULT 'MT',
  `dp_prefix` VARCHAR(10) NOT NULL DEFAULT 'DP',
  `au_prefix` VARCHAR(10) NOT NULL DEFAULT 'AU',
  `currency` VARCHAR(8) NOT NULL DEFAULT 'THB',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ast_set_owner_trial_uidx` (`owner_id`, `trial_session_id`),
  CONSTRAINT `asset_settings_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
